# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5158eb99f76d97e4faf79957e25b378312cfed57e9b54f3b7b815c173ded29e4ff3c81b66172df366a7169cc07e492d7f666f1f339b4ae6c2cff10abf999faf3

test:
  secret_key_base: ca57e30eea6db42a6d25fdf49eac2737dafd61f3c01106f150689c9f64c57b5f43f105ed3801e6babc5598a75b4ee186700208aad2a455564ba0e5cd1d5dbaeb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
